export const regionSlugMap: { [key: string]: string } = {
  // 서울 - 강남구
  '삼성동': 'samsung-dong',
  '역삼동': 'yeoksam-dong',
  '논현동': 'nonhyeon-dong',
  '청담동': 'cheongdam-dong',
  '대치동': 'daechi-dong',
  '신사동': 'sinsa-dong',
  '압구정동': 'apgujeong-dong',
  '도곡동': 'dogok-dong',
  '개포동': 'gaepo-dong',
  '세곡동': 'segok-dong',
  '강남동': 'gangnam-dong',
  
  // 서울 - 서초구
  '서초동': 'seocho-dong',
  '잠원동': 'jamwon-dong',
  '반포동': 'banpo-dong',
  '방배동': 'bangbae-dong',
  '양재동': 'yangjae-dong',
  '우면동': 'umyeon-dong',
  '내곡동': 'naegok-dong',
  
  // 서울 - 송파구
  '잠실동': 'jamsil-dong',
  '신천동': 'sincheon-dong',
  '풍납동': 'pungnap-dong',
  '송파동': 'songpa-dong',
  '석촌동': 'seokchon-dong',
  '삼전동': 'samjeon-dong',
  '가락동': 'garak-dong',
  '문정동': 'munjeong-dong',
  '장지동': 'jangji-dong',
  '방이동': 'bangi-dong',
  '오금동': 'ogeum-dong',
  
  // 서울 - 강동구
  '명일동': 'myeongil-dong',
  '고덕동': 'godeok-dong',
  '상일동': 'sangil-dong',
  '길동': 'gil-dong',
  '둔촌동': 'dunchon-dong',
  '암사동': 'amsa-dong',
  '성내동': 'seongnae-dong',
  '천호동': 'cheonho-dong',
  '강일동': 'gangil-dong',
  
  // 서울 - 마포구
  '아현동': 'ahyeon-dong',
  '공덕동': 'gongdeok-dong',
  '도화동': 'dohwa-dong',
  '용강동': 'yonggang-dong',
  '대흥동': 'daeheung-dong',
  '염리동': 'yeomni-dong',
  '신수동': 'sinsu-dong',
  '서강동': 'seogang-dong',
  '서교동': 'seogyo-dong',
  '합정동': 'hapjeong-dong',
  '망원동': 'mangwon-dong',
  '연남동': 'yeonnam-dong',
  '성산동': 'seongsan-dong',
  '상암동': 'sangam-dong',
  '마포동': 'mapo-dong',
  '상수동': 'sangsu-dong',
  
  // 서울 - 용산구
  '후암동': 'huam-dong',
  '용산동': 'yongsan-dong',
  '남영동': 'namyeong-dong',
  '청파동': 'cheongpa-dong',
  '원효로': 'wonhyo-ro',
  '효창동': 'hyochang-dong',
  '도원동': 'dowon-dong',
  '문배동': 'munbae-dong',
  '한강로동': 'hangangno-dong',
  '이촌동': 'ichon-dong',
  '이태원동': 'itaewon-dong',
  '한남동': 'hannam-dong',
  '서빙고동': 'seobinggo-dong',
  '보광동': 'bogwang-dong',
  
  // 서울 - 영등포구
  '영등포동': 'yeongdeungpo-dong',
  '여의도동': 'yeouido-dong',
  '당산동': 'dangsan-dong',
  '도림동': 'dorim-dong',
  '문래동': 'mullae-dong',
  '양평동': 'yangpyeong-dong',
  '신길동': 'singil-dong',
  '대림동': 'daerim-dong',
  
  // 서울 - 강서구
  '염창동': 'yeomchang-dong',
  '등촌동': 'deungchon-dong',
  '화곡동': 'hwagok-dong',
  '가양동': 'gayang-dong',
  '마곡동': 'magok-dong',
  '내발산동': 'naebalsan-dong',
  '외발산동': 'oebalsan-dong',
  '공항동': 'gonghang-dong',
  '방화동': 'banghwa-dong',
  '개화동': 'gaehwa-dong',
  '발산동': 'balsan-dong',
  
  // 서울 - 구로구
  '신도림동': 'sindorim-dong',
  '구로동': 'guro-dong',
  '가리봉동': 'garibong-dong',
  '고척동': 'gocheok-dong',
  '개봉동': 'gaebong-dong',
  '오류동': 'oryu-dong',
  '천왕동': 'cheonwang-dong',
  '항동': 'hang-dong',
  '가산동': 'gasan-dong',
  
  // 서울 - 금천구
  '가산디지털단지': 'gasan-digital-danji',
  '시흥동': 'siheung-dong',
  '독산동': 'doksan-dong',
  
  // 서울 - 관악구
  '봉천동': 'bongcheon-dong',
  '신림동': 'sillim-dong',
  '남현동': 'namhyeon-dong',
  '낙성대동': 'nakseongdae-dong',
  
  // 서울 - 동작구
  '노량진동': 'noryangjin-dong',
  '상도동': 'sangdo-dong',
  '흑석동': 'heukseok-dong',
  '사당동': 'sadang-dong',
  '대방동': 'daebang-dong',
  '신대방동': 'sindaebang-dong',
  
  // 서울 - 성동구
  '왕십리동': 'wangsimni-dong',
  '마장동': 'majang-dong',
  '사근동': 'sageun-dong',
  '행당동': 'haengdang-dong',
  '응봉동': 'eungbong-dong',
  '금호동': 'geumho-dong',
  '옥수동': 'oksu-dong',
  '성수동': 'seongsu-dong',
  '송정동': 'songjeong-dong',
  '용답동': 'yongdap-dong',
  
  // 서울 - 광진구
  '중곡동': 'junggok-dong',
  '능동': 'neung-dong',
  '구의동': 'guui-dong',
  '광장동': 'gwangjang-dong',
  '자양동': 'jayang-dong',
  '화양동': 'hwayang-dong',
  '광진동': 'gwangjin-dong',
  
  // 서울 - 중구
  '소공동': 'sogong-dong',
  '회현동': 'hoehyeon-dong',
  '명동': 'myeong-dong',
  '필동': 'pil-dong',
  '장충동': 'jangchung-dong',
  '광희동': 'gwanghui-dong',
  '을지로동': 'euljiro-dong',
  '신당동': 'sindang-dong',
  '다산동': 'dasan-dong',
  '약수동': 'yaksu-dong',
  '청구동': 'cheonggu-dong',
  '동화동': 'donghwa-dong',
  '황학동': 'hwanghak-dong',
  '중림동': 'jungnim-dong',
  
  // 서울 - 종로구
  '청운동': 'cheongun-dong',
  '신교동': 'singyo-dong',
  '궁정동': 'gungjeong-dong',
  '효자동': 'hyoja-dong',
  '창성동': 'changseong-dong',
  '통의동': 'tongui-dong',
  '적선동': 'jeokseon-dong',
  '통인동': 'tongin-dong',
  '누상동': 'nusang-dong',
  '삼청동': 'samcheong-dong',
  '안국동': 'anguk-dong',
  '소격동': 'sogyeok-dong',
  '화동': 'hwa-dong',
  '사간동': 'sagan-dong',
  '송현동': 'songhyeon-dong',
  '가회동': 'gahoe-dong',
  '재동': 'jae-dong',
  '계동': 'gye-dong',
  '원서동': 'wonseo-dong',
  '인사동': 'insa-dong',
  '익선동': 'ikseon-dong',
  '경운동': 'gyeongun-dong',
  '관훈동': 'gwanhun-dong',
  '낙원동': 'nagwon-dong',
  '종로1가~6가': 'jongno',
  '이화동': 'ihwa-dong',
  '연지동': 'yeonji-dong',
  '동숭동': 'dongsung-dong',
  '혜화동': 'hyehwa-dong',
  '명륜1~4가': 'myeongnyun',
  
  // 경기 - 성남시
  '분당구 서현동': 'bundang-gu-seohyeon-dong',
  '분당구 정자동': 'bundang-gu-jeongja-dong',
  '분당구 수내동': 'bundang-gu-sunae-dong',
  '분당구 야탑동': 'bundang-gu-yatap-dong',
  '분당구 이매동': 'bundang-gu-imae-dong',
  '수정구 신흥동': 'sujeong-gu-sinheung-dong',
  '수정구 수진동': 'sujeong-gu-sujin-dong',
  '수정구 단대동': 'sujeong-gu-dandae-dong',
  '수정구 태평동': 'sujeong-gu-taepyeong-dong',
  '중원구 성남동': 'jungwon-gu-seongnam-dong',
  '중원구 금광동': 'jungwon-gu-geumgwang-dong',
  '중원구 은행동': 'jungwon-gu-eunhaeng-dong',
  '중원구 상대원동': 'jungwon-gu-sangdaewon-dong',
  
  // 경기 - 수원시
  '장안구 파장동': 'jangan-gu-pajang-dong',
  '장안구 정자동': 'jangan-gu-jeongja-dong',
  '장안구 송죽동': 'jangan-gu-songjuk-dong',
  '장안구 조원동': 'jangan-gu-jowon-dong',
  '장안구 연무동': 'jangan-gu-yeonmu-dong',
  '권선구 세류동': 'gwonseon-gu-seryu-dong',
  '권선구 평동': 'gwonseon-gu-pyeong-dong',
  '권선구 서둔동': 'gwonseon-gu-seodun-dong',
  '권선구 구운동': 'gwonseon-gu-guun-dong',
  '팔달구 매산동': 'paldal-gu-maesan-dong',
  '팔달구 매교동': 'paldal-gu-maegyo-dong',
  '팔달구 인계동': 'paldal-gu-ingye-dong',
  '팔달구 우만동': 'paldal-gu-uman-dong',
  '영통구 영통동': 'yeongtong-gu-yeongtong-dong',
  '영통구 망포동': 'yeongtong-gu-mangpo-dong',
  '영통구 매탄동': 'yeongtong-gu-maetan-dong',
  '영통구 원천동': 'yeongtong-gu-woncheon-dong',
  '영통구 광교동': 'yeongtong-gu-gwanggyo-dong',
  
  // 경기 - 고양시
  '일산동구 백석동': 'ilsandong-gu-baekseok-dong',
  '일산동구 마두동': 'ilsandong-gu-madu-dong',
  '일산동구 장항동': 'ilsandong-gu-janghang-dong',
  '일산동구 식사동': 'ilsandong-gu-siksa-dong',
  '일산서구 주엽동': 'ilsanseo-gu-juyeop-dong',
  '일산서구 대화동': 'ilsanseo-gu-daeghwa-dong',
  '일산서구 탄현동': 'ilsanseo-gu-tanhyeon-dong',
  '덕양구 화정동': 'deogyang-gu-hwajeong-dong',
  '덕양구 행신동': 'deogyang-gu-haengsin-dong',
  '덕양구 능곡동': 'deogyang-gu-neunggok-dong',
  '덕양구 원당동': 'deogyang-gu-wondang-dong',
  '덕양구 삼송동': 'deogyang-gu-samsong-dong',
  
  // 경기 - 용인시
  '수지구 죽전동': 'suji-gu-jukjeon-dong',
  '수지구 동천동': 'suji-gu-dongcheon-dong',
  '수지구 신봉동': 'suji-gu-sinbong-dong',
  '수지구 상현동': 'suji-gu-sanghyeon-dong',
  '기흥구 구갈동': 'giheung-gu-gugal-dong',
  '기흥구 보정동': 'giheung-gu-bojeong-dong',
  '기흥구 신갈동': 'giheung-gu-singal-dong',
  '기흥구 영덕동': 'giheung-gu-yeongdeok-dong',
  '처인구 김량장동': 'cheoin-gu-gimryangjang-dong',
  '처인구 역북동': 'cheoin-gu-yeokbuk-dong',
  '처인구 유방동': 'cheoin-gu-yubang-dong',
  '처인구 포곡읍': 'cheoin-gu-pogok-eup',
  '처인구 모현읍': 'cheoin-gu-mohyeon-eup',
  
  // 경기 - 부천시
  '원미구 중동': 'wonmi-gu-jung-dong',
  '원미구 상동': 'wonmi-gu-sang-dong',
  '원미구 심곡동': 'wonmi-gu-simgok-dong',
  '원미구 약대동': 'wonmi-gu-yakdae-dong',
  '소사구 소사본동': 'sosa-gu-sosabon-dong',
  '소사구 송내동': 'sosa-gu-songnae-dong',
  '소사구 괴안동': 'sosa-gu-goean-dong',
  '오정구 오정동': 'ojeong-gu-ojeong-dong',
  '오정구 고강동': 'ojeong-gu-gogang-dong',
  '오정구 원종동': 'ojeong-gu-wonjong-dong',
  
  // 경기 - 안산시
  '단원구 고잔동': 'danwon-gu-gojan-dong',
  '단원구 초지동': 'danwon-gu-choji-dong',
  '단원구 원곡동': 'danwon-gu-wongok-dong',
  '단원구 선부동': 'danwon-gu-seonbu-dong',
  '상록구 본오동': 'sangnok-gu-bono-dong',
  '상록구 사동': 'sangnok-gu-sa-dong',
  '상록구 월피동': 'sangnok-gu-wolpi-dong',
  '상록구 건건동': 'sangnok-gu-geongeon-dong',
  '상록구 성포동': 'sangnok-gu-seongpo-dong',
  
  // 경기 - 화성시
  '동탄1신도시': 'dongtan1',
  '동탄2신도시': 'dongtan2',
  '병점동': 'byeongjeom-dong',
  '향남읍': 'hyangnam-eup',
  '봉담읍': 'bongdam-eup',
  '우정읍': 'ujeong-eup',
  '남양읍': 'namyang-eup',
  
  // 경기 - 남양주시
  '다산동': 'dasan-dong',
  '별내동': 'byeollae-dong',
  '화도읍': 'hwado-eup',
  '진접읍': 'jinjeop-eup',
  '오남읍': 'onam-eup',
  '평내동': 'pyeongnae-dong',
  '금곡동': 'geumgok-dong',
  '양정동': 'yangjeong-dong',
  
  // 경기 - 평택시
  '평택동': 'pyeongtaek-dong',
  '송탄동': 'songtan-dong',
  '서정동': 'seojeong-dong',
  '지산동': 'jisan-dong',
  '소사벌': 'sosabeol',
  '고덕신도시': 'godeok-sindo',
  '청북읍': 'cheongbuk-eup',
  '안중읍': 'anjung-eup',
  
  // 경기 - 안양시
  '만안구 안양동': 'manan-gu-anyang-dong',
  '만안구 석수동': 'manan-gu-seoksu-dong',
  '동안구 비산동': 'dongan-gu-bisan-dong',
  '동안구 관양동': 'dongan-gu-gwanyang-dong',
  '동안구 평촌동': 'dongan-gu-pyeongchon-dong',
  '동안구 호계동': 'dongan-gu-hogye-dong',
  '동안구 범계동': 'dongan-gu-beomgye-dong',
  
  // 경기 - 시흥시
  '정왕동': 'jeongwang-dong',
  '대야동': 'daeya-dong',
  '신천동': 'sincheon-dong',
  '은행동': 'eunhaeng-dong',
  '장곡동': 'janggok-dong',
  '월곶동': 'wolgot-dong',
  
  // 경기 - 파주시
  '운정동': 'unjeong-dong',
  '금촌동': 'geumchon-dong',
  '교하읍': 'gyoha-eup',
  '문산읍': 'munsan-eup',
  '조리읍': 'jori-eup',
  
  // 경기 - 의정부시
  '의정부동': 'uijeongbu-dong',
  '호원동': 'howon-dong',
  '장암동': 'jangam-dong',
  '신곡동': 'singok-dong',
  '가능동': 'ganeung-dong',
  '녹양동': 'nogyang-dong',
  
  // 경기 - 김포시
  '장기동': 'janggi-dong',
  '구래동': 'gurae-dong',
  '마산동': 'masan-dong',
  '사우동': 'sau-dong',
  '풍무동': 'pungmu-dong',
  '고촌읍': 'gochon-eup',
  '양촌읍': 'yangchon-eup',
  
  // 경기 - 광주시
  '경안동': 'gyeongan-dong',
  '송정동': 'songjeong-dong',
  '쌍령동': 'ssangnyeong-dong',
  '역동': 'yeok-dong',
  '탄벌동': 'tanbeol-dong',
  '오포읍': 'opo-eup',
  '곤지암읍': 'gonjiam-eup',
  
  // 경기 - 광명시
  '철산동': 'cheolsan-dong',
  '광명동': 'gwangmyeong-dong',
  '하안동': 'haan-dong',
  '소하동': 'soha-dong',
  
  // 경기 - 군포시
  '산본동': 'sanbon-dong',
  '금정동': 'geumjeong-dong',
  '당정동': 'dangjeong-dong',
  '당동': 'dang-dong',
  '군포동': 'gunpo-dong',
  
  // 경기 - 하남시
  '신장동': 'sinjang-dong',
  '감북동': 'gambuk-dong',
  '감일동': 'gamil-dong',
  '창우동': 'changwoo-dong',
  '덕풍동': 'deokpung-dong',
  '미사동': 'misa-dong',
  
  // 경기 - 오산시
  '오산동': 'osan-dong',
  '원동': 'won-dong',
  '세교동': 'segyo-dong',
  '갈곶동': 'galgot-dong',
  
  // 경기 - 이천시
  '중리동': 'jungri-dong',
  '창전동': 'changjeon-dong',
  '관고동': 'gwango-dong',
  '증포동': 'jeungpo-dong',
  '부발읍': 'bubal-eup',
  '신둔면': 'sindun-myeon',
  
  // 인천 - 남동구
  '구월동': 'guwol-dong',
  '간석동': 'ganseok-dong',
  '만수동': 'mansu-dong',
  '장수동': 'jangsu-dong',
  '서창동': 'seochang-dong',
  '운연동': 'unyeon-dong',
  
  // 인천 - 연수구
  '송도동': 'songdo-dong',
  '옥련동': 'okyeon-dong',
  '동춘동': 'dongchun-dong',
  '청학동': 'cheonghak-dong',
  '선학동': 'seonhak-dong',
  '연수동': 'yeonsu-dong',
  
  // 인천 - 부평구
  '부평동': 'bupyeong-dong',
  '산곡동': 'sangok-dong',
  '청천동': 'cheongcheon-dong',
  '갈산동': 'galsan-dong',
  '삼산동': 'samsan-dong',
  '부개동': 'bugae-dong',
  '십정동': 'sipjeong-dong',
  
  // 인천 - 계양구
  '작전동': 'jakjeon-dong',
  '효성동': 'hyoseong-dong',
  '계산동': 'gyesan-dong',
  '임학동': 'imhak-dong',
  '동양동': 'dongyang-dong',
  '귤현동': 'gyulhyeon-dong',
  '병방동': 'byeongbang-dong',
  '박촌동': 'bakchon-dong',
  
  // 인천 - 서구
  '검단동': 'geomdan-dong',
  '원당동': 'wondang-dong',
  '가좌동': 'gajwa-dong',
  '석남동': 'seoknam-dong',
  '가정동': 'gajeong-dong-incheon',
  '신현동': 'sinhyeon-dong',
  '검암동': 'geomam-dong',
  '연희동': 'yeonhui-dong-incheon',
  
  // 인천 - 미추홀구
  '숭의동': 'sungui-dong',
  '용현동': 'yonghyeon-dong',
  '학익동': 'hakik-dong',
  '주안동': 'juan-dong',
  '관교동': 'gwangyo-dong',
  '문학동': 'munhak-dong',
  
  // 인천 - 중구
  '신포동': 'sinpo-dong',
  '답동': 'dap-dong',
  '연안동': 'yeonan-dong',
  '신생동': 'sinsaeng-dong',
  '북성동': 'bukseong-dong',
  '선화동': 'seonhwa-dong',
  '유동': 'yu-dong',
  '송월동': 'songwol-dong',
  '송림동': 'songlim-dong-incheon',
  '영종도': 'yeongjongdo',
  '용유도': 'yongyudo',
  
  // 인천 - 동구
  '만석동': 'manseok-dong',
  '화수동': 'hwasu-dong',
  '송현동': 'songhyeon-dong-incheon',
  '금곡동': 'geumgok-dong-incheon',
  '화평동': 'hwapyeong-dong',
  
  // 경상도 - 부산
  '해운대구': 'haeundae-gu',
  '남구': 'nam-gu',
  '동래구': 'dongnae-gu',
  '부산진구': 'busanjin-gu',
  '수영구': 'suyeong-gu',
  '연제구': 'yeonje-gu',
  '사상구': 'sasang-gu',
  '사하구': 'saha-gu',
  '강서구': 'gangseo-gu',
  '금정구': 'geumjeong-gu',
  '북구': 'buk-gu',
  '서구': 'seo-gu',
  '중구': 'jung-gu',
  '동구': 'dong-gu',
  '영도구': 'yeongdo-gu',
  
  // 경상도 - 대구
  '수성구': 'suseong-gu',
  '달서구': 'dalseo-gu',
  '달성군': 'dalseong-gun',
  
  // 경상도 - 울산
  '울주군': 'ulju-gun',
  
  // 경상도 - 경남
  '창원시 의창구': 'changwon-ui-chang-gu',
  '창원시 성산구': 'changwon-eui-seongsan-gu',
  '창원시 마산회원구': 'changwon-eui-masanhwop-gu',
  '창원시 마산합포구': 'changwon-eui-masanhap-gu',
  '창원시 진해구': 'changwon-eui-jinhae-gu',
  '김해시': 'gimhae-si',
  '양산시': 'yangsan-si',
  '진주시': 'jinju-si',
  '거제시': 'geoje-si',
  '통영시': 'tongyeong-si',
  '사천시': 'sacheon-si',
  '밀양시': 'miryang-si',
  '함안군': 'haman-gun',
  '거창군': 'geochang-gun',
  '창녕군': 'changnyeong-gun',
  '고성군': 'goseong-gun',
  '하동군': 'hadong-gun',
  '합천군': 'hapcheon-gun',
  '남해군': 'namhae-gun',
  '함양군': 'hamyang-gun',
  '산청군': 'sancheong-gun',
  '의령군': 'uiryeong-gun',
  
  // 경상도 - 경북
  '포항시 남구': 'pohang-nam-gu',
  '포항시 북구': 'pohang-buk-gu',
  '경주시': 'gyeongju-si',
  '구미시': 'gumi-si',
  '안동시': 'andong-si',
  '경산시': 'gyeongsan-si',
  '영천시': 'yeongcheon-si',
  '상주시': 'sangju-si',
  '문경시': 'mungyeong-si',
  '김천시': 'gimcheon-si',
  '영주시': 'yeongju-si',
  '칠곡군': 'chilgok-gun',
  '영덕군': 'yeongdeok-gun',
  '청송군': 'cheongsong-gun',
  '고령군': 'goryeong-gun',
  '성주군': 'seongju-gun',
  '예천군': 'yecheon-gun',
  '봉화군': 'bonghwa-gun',
  '울진군': 'uljin-gun',
  '의성군': 'uiseong-gun',
  '청도군': 'cheongdo-gun',
  '군위군': 'gunwi-gun',
  
  // 전라도 - 광주
  '서구': 'gwangju-seo',
  '광산구': 'gwangju-gwangsan',
  
  // 전라도 - 전북
  '전주시 완산구': 'jeonju-wansan',
  '전주시 덕진구': 'jeonju-deokjin',
  '익산시': 'iksan',
  '군산시': 'gunsan',
  '정읍시': 'jeongeup',
  '남원시': 'namwon',
  '김제시': 'gimje',
  '완주군': 'wanju',
  '임실군': 'imsil',
  '순창군': 'sunchang',
  '고창군': 'gochang',
  '부안군': 'buan',
  '무주군': 'muju',
  '진안군': 'jinan',
  '장수군': 'jangsu',
  
  // 전라도 - 전남
  '목포시': 'mokpo',
  '여수시': 'yeosu',
  '순천시': 'suncheon',
  '나주시': 'naju',
  '광양시': 'gwangyang',
  '담양군': 'damyang',
  '곡성군': 'gokseong',
  '구례군': 'gurye',
  '고흥군': 'goheung',
  '보성군': 'boseong',
  '화순군': 'hwasun',
  '장흥군': 'jangheung',
  '강진군': 'gangjin',
  '해남군': 'haenam',
  '영암군': 'yeongam',
  '무안군': 'muan',
  '함평군': 'hampyeong',
  '영광군': 'yeonggwang',
  '장성군': 'jangseong',
  '완도군': 'wando',
  '진도군': 'jindo',
  '신안군': 'sinan',
}

export function areaToSlug(area: string): string {
  const cleanArea = area.replace('출장마사지', '').trim()
  return regionSlugMap[cleanArea] || cleanArea.toLowerCase().replace(/\s+/g, '-')
}
