export const regionData: { [key: string]: { regionName: string; districtName: string; areaName: string } } = {
  // 서울 - 강남구
  'samsung-dong': { regionName: '서울', districtName: '강남구', areaName: '삼성동' },
  'yeoksam-dong': { regionName: '서울', districtName: '강남구', areaName: '역삼동' },
  'nonhyeon-dong': { regionName: '서울', districtName: '강남구', areaName: '논현동' },
  'cheongdam-dong': { regionName: '서울', districtName: '강남구', areaName: '청담동' },
  'daechi-dong': { regionName: '서울', districtName: '강남구', areaName: '대치동' },
  'sinsa-dong': { regionName: '서울', districtName: '강남구', areaName: '신사동' },
  'apgujeong-dong': { regionName: '서울', districtName: '강남구', areaName: '압구정동' },
  'dogok-dong': { regionName: '서울', districtName: '강남구', areaName: '도곡동' },
  'gaepo-dong': { regionName: '서울', districtName: '강남구', areaName: '개포동' },
  'segok-dong': { regionName: '서울', districtName: '강남구', areaName: '세곡동' },
  'gangnam-dong': { regionName: '서울', districtName: '강남구', areaName: '강남동' },
  
  // 서울 - 서초구
  'seocho-dong': { regionName: '서울', districtName: '서초구', areaName: '서초동' },
  'jamwon-dong': { regionName: '서울', districtName: '서초구', areaName: '잠원동' },
  'banpo-dong': { regionName: '서울', districtName: '서초구', areaName: '반포동' },
  'bangbae-dong': { regionName: '서울', districtName: '서초구', areaName: '방배동' },
  'yangjae-dong': { regionName: '서울', districtName: '서초구', areaName: '양재동' },
  'umyeon-dong': { regionName: '서울', districtName: '서초구', areaName: '우면동' },
  'naegok-dong': { regionName: '서울', districtName: '서초구', areaName: '내곡동' },
  
  // 서울 - 송파구
  'jamsil-dong': { regionName: '서울', districtName: '송파구', areaName: '잠실동' },
  'sincheon-dong': { regionName: '서울', districtName: '송파구', areaName: '신천동' },
  'pungnap-dong': { regionName: '서울', districtName: '송파구', areaName: '풍납동' },
  'songpa-dong': { regionName: '서울', districtName: '송파구', areaName: '송파동' },
  'seokchon-dong': { regionName: '서울', districtName: '송파구', areaName: '석촌동' },
  'samjeon-dong': { regionName: '서울', districtName: '송파구', areaName: '삼전동' },
  'garak-dong': { regionName: '서울', districtName: '송파구', areaName: '가락동' },
  'munjeong-dong': { regionName: '서울', districtName: '송파구', areaName: '문정동' },
  'jangji-dong': { regionName: '서울', districtName: '송파구', areaName: '장지동' },
  'bangi-dong': { regionName: '서울', districtName: '송파구', areaName: '방이동' },
  'ogeum-dong': { regionName: '서울', districtName: '송파구', areaName: '오금동' },
  
  // 서울 - 강동구
  'myeongil-dong': { regionName: '서울', districtName: '강동구', areaName: '명일동' },
  'godeok-dong': { regionName: '서울', districtName: '강동구', areaName: '고덕동' },
  'sangil-dong': { regionName: '서울', districtName: '강동구', areaName: '상일동' },
  'gil-dong': { regionName: '서울', districtName: '강동구', areaName: '길동' },
  'dunchon-dong': { regionName: '서울', districtName: '강동구', areaName: '둔촌동' },
  'amsa-dong': { regionName: '서울', districtName: '강동구', areaName: '암사동' },
  'seongnae-dong': { regionName: '서울', districtName: '강동구', areaName: '성내동' },
  'cheonho-dong': { regionName: '서울', districtName: '강동구', areaName: '천호동' },
  'gangil-dong': { regionName: '서울', districtName: '강동구', areaName: '강일동' },
  
  // 서울 - 마포구
  'ahyeon-dong': { regionName: '서울', districtName: '마포구', areaName: '아현동' },
  'gongdeok-dong': { regionName: '서울', districtName: '마포구', areaName: '공덕동' },
  'dohwa-dong': { regionName: '서울', districtName: '마포구', areaName: '도화동' },
  'yonggang-dong': { regionName: '서울', districtName: '마포구', areaName: '용강동' },
  'daeheung-dong': { regionName: '서울', districtName: '마포구', areaName: '대흥동' },
  'yeomni-dong': { regionName: '서울', districtName: '마포구', areaName: '염리동' },
  'sinsu-dong': { regionName: '서울', districtName: '마포구', areaName: '신수동' },
  'seogang-dong': { regionName: '서울', districtName: '마포구', areaName: '서강동' },
  'seogyo-dong': { regionName: '서울', districtName: '마포구', areaName: '서교동' },
  'hapjeong-dong': { regionName: '서울', districtName: '마포구', areaName: '합정동' },
  'mangwon-dong': { regionName: '서울', districtName: '마포구', areaName: '망원동' },
  'yeonnam-dong': { regionName: '서울', districtName: '마포구', areaName: '연남동' },
  'seongsan-dong': { regionName: '서울', districtName: '마포구', areaName: '성산동' },
  'sangam-dong': { regionName: '서울', districtName: '마포구', areaName: '상암동' },
  'mapo-dong': { regionName: '서울', districtName: '마포구', areaName: '마포동' },
  'sangsu-dong': { regionName: '서울', districtName: '마포구', areaName: '상수동' },
  
  // 서울 - 용산구
  'huam-dong': { regionName: '서울', districtName: '용산구', areaName: '후암동' },
  'yongsan-dong': { regionName: '서울', districtName: '용산구', areaName: '용산동' },
  'namyeong-dong': { regionName: '서울', districtName: '용산구', areaName: '남영동' },
  'cheongpa-dong': { regionName: '서울', districtName: '용산구', areaName: '청파동' },
  'wonhyo-ro': { regionName: '서울', districtName: '용산구', areaName: '원효로' },
  'hyochang-dong': { regionName: '서울', districtName: '용산구', areaName: '효창동' },
  'dowon-dong': { regionName: '서울', districtName: '용산구', areaName: '도원동' },
  'munbae-dong': { regionName: '서울', districtName: '용산구', areaName: '문배동' },
  'hangangno-dong': { regionName: '서울', districtName: '용산구', areaName: '한강로동' },
  'ichon-dong': { regionName: '서울', districtName: '용산구', areaName: '이촌동' },
  'itaewon-dong': { regionName: '서울', districtName: '용산구', areaName: '이태원동' },
  'hannam-dong': { regionName: '서울', districtName: '용산구', areaName: '한남동' },
  'seobinggo-dong': { regionName: '서울', districtName: '용산구', areaName: '서빙고동' },
  'bogwang-dong': { regionName: '서울', districtName: '용산구', areaName: '보광동' },
  
  // 서울 - 영등포구
  'yeongdeungpo-dong': { regionName: '서울', districtName: '영등포구', areaName: '영등포동' },
  'yeouido-dong': { regionName: '서울', districtName: '영등포구', areaName: '여의도동' },
  'dangsan-dong': { regionName: '서울', districtName: '영등포구', areaName: '당산동' },
  'dorim-dong': { regionName: '서울', districtName: '영등포구', areaName: '도림동' },
  'mullae-dong': { regionName: '서울', districtName: '영등포구', areaName: '문래동' },
  'yangpyeong-dong': { regionName: '서울', districtName: '영등포구', areaName: '양평동' },
  'singil-dong': { regionName: '서울', districtName: '영등포구', areaName: '신길동' },
  'daerim-dong': { regionName: '서울', districtName: '영등포구', areaName: '대림동' },
  
  // 서울 - 강서구
  'yeomchang-dong': { regionName: '서울', districtName: '강서구', areaName: '염창동' },
  'deungchon-dong': { regionName: '서울', districtName: '강서구', areaName: '등촌동' },
  'hwagok-dong': { regionName: '서울', districtName: '강서구', areaName: '화곡동' },
  'gayang-dong': { regionName: '서울', districtName: '강서구', areaName: '가양동' },
  'magok-dong': { regionName: '서울', districtName: '강서구', areaName: '마곡동' },
  'naebalsan-dong': { regionName: '서울', districtName: '강서구', areaName: '내발산동' },
  'oebalsan-dong': { regionName: '서울', districtName: '강서구', areaName: '외발산동' },
  'gonghang-dong': { regionName: '서울', districtName: '강서구', areaName: '공항동' },
  'banghwa-dong': { regionName: '서울', districtName: '강서구', areaName: '방화동' },
  'gaehwa-dong': { regionName: '서울', districtName: '강서구', areaName: '개화동' },
  'balsan-dong': { regionName: '서울', districtName: '강서구', areaName: '발산동' },
  
  // 서울 - 구로구
  'sindorim-dong': { regionName: '서울', districtName: '구로구', areaName: '신도림동' },
  'guro-dong': { regionName: '서울', districtName: '구로구', areaName: '구로동' },
  'garibong-dong': { regionName: '서울', districtName: '구로구', areaName: '가리봉동' },
  'gocheok-dong': { regionName: '서울', districtName: '구로구', areaName: '고척동' },
  'gaebong-dong': { regionName: '서울', districtName: '구로구', areaName: '개봉동' },
  'oryu-dong': { regionName: '서울', districtName: '구로구', areaName: '오류동' },
  'cheonwang-dong': { regionName: '서울', districtName: '구로구', areaName: '천왕동' },
  'hang-dong': { regionName: '서울', districtName: '구로구', areaName: '항동' },
  'gasan-dong': { regionName: '서울', districtName: '구로구', areaName: '가산동' },
  
  // 서울 - 금천구
  'gasan-digital-danji': { regionName: '서울', districtName: '금천구', areaName: '가산디지털단지' },
  'siheung-dong': { regionName: '서울', districtName: '금천구', areaName: '시흥동' },
  'doksan-dong': { regionName: '서울', districtName: '금천구', areaName: '독산동' },
  
  // 서울 - 관악구
  'bongcheon-dong': { regionName: '서울', districtName: '관악구', areaName: '봉천동' },
  'sillim-dong': { regionName: '서울', districtName: '관악구', areaName: '신림동' },
  'namhyeon-dong': { regionName: '서울', districtName: '관악구', areaName: '남현동' },
  'nakseongdae-dong': { regionName: '서울', districtName: '관악구', areaName: '낙성대동' },
  
  // 서울 - 동작구
  'noryangjin-dong': { regionName: '서울', districtName: '동작구', areaName: '노량진동' },
  'sangdo-dong': { regionName: '서울', districtName: '동작구', areaName: '상도동' },
  'heukseok-dong': { regionName: '서울', districtName: '동작구', areaName: '흑석동' },
  'sadang-dong': { regionName: '서울', districtName: '동작구', areaName: '사당동' },
  'daebang-dong': { regionName: '서울', districtName: '동작구', areaName: '대방동' },
  'sindaebang-dong': { regionName: '서울', districtName: '동작구', areaName: '신대방동' },
  
  // 서울 - 성동구
  'wangsimni-dong': { regionName: '서울', districtName: '성동구', areaName: '왕십리동' },
  'majang-dong': { regionName: '서울', districtName: '성동구', areaName: '마장동' },
  'sageun-dong': { regionName: '서울', districtName: '성동구', areaName: '사근동' },
  'haengdang-dong': { regionName: '서울', districtName: '성동구', areaName: '행당동' },
  'eungbong-dong': { regionName: '서울', districtName: '성동구', areaName: '응봉동' },
  'geumho-dong': { regionName: '서울', districtName: '성동구', areaName: '금호동' },
  'oksu-dong': { regionName: '서울', districtName: '성동구', areaName: '옥수동' },
  'seongsu-dong': { regionName: '서울', districtName: '성동구', areaName: '성수동' },
  'songjeong-dong': { regionName: '서울', districtName: '성동구', areaName: '송정동' },
  'yongdap-dong': { regionName: '서울', districtName: '성동구', areaName: '용답동' },
  
  // 서울 - 광진구
  'junggok-dong': { regionName: '서울', districtName: '광진구', areaName: '중곡동' },
  'neung-dong': { regionName: '서울', districtName: '광진구', areaName: '능동' },
  'guui-dong': { regionName: '서울', districtName: '광진구', areaName: '구의동' },
  'gwangjang-dong': { regionName: '서울', districtName: '광진구', areaName: '광장동' },
  'jayang-dong': { regionName: '서울', districtName: '광진구', areaName: '자양동' },
  'hwayang-dong': { regionName: '서울', districtName: '광진구', areaName: '화양동' },
  'gwangjin-dong': { regionName: '서울', districtName: '광진구', areaName: '광진동' },
  
  // 서울 - 중구
  'sogong-dong': { regionName: '서울', districtName: '중구', areaName: '소공동' },
  'hoehyeon-dong': { regionName: '서울', districtName: '중구', areaName: '회현동' },
  'myeong-dong': { regionName: '서울', districtName: '중구', areaName: '명동' },
  'pil-dong': { regionName: '서울', districtName: '중구', areaName: '필동' },
  'jangchung-dong': { regionName: '서울', districtName: '중구', areaName: '장충동' },
  'gwanghui-dong': { regionName: '서울', districtName: '중구', areaName: '광희동' },
  'euljiro-dong': { regionName: '서울', districtName: '중구', areaName: '을지로동' },
  'sindang-dong': { regionName: '서울', districtName: '중구', areaName: '신당동' },
  'dasan-dong': { regionName: '서울', districtName: '중구', areaName: '다산동' },
  'yaksu-dong': { regionName: '서울', districtName: '중구', areaName: '약수동' },
  'cheonggu-dong': { regionName: '서울', districtName: '중구', areaName: '청구동' },
  'donghwa-dong': { regionName: '서울', districtName: '중구', areaName: '동화동' },
  'hwanghak-dong': { regionName: '서울', districtName: '중구', areaName: '황학동' },
  'jungnim-dong': { regionName: '서울', districtName: '중구', areaName: '중림동' },
  
  // 서울 - 종로구
  'cheongun-dong': { regionName: '서울', districtName: '종로구', areaName: '청운동' },
  'singyo-dong': { regionName: '서울', districtName: '종로구', areaName: '신교동' },
  'gungjeong-dong': { regionName: '서울', districtName: '종로구', areaName: '궁정동' },
  'hyoja-dong': { regionName: '서울', districtName: '종로구', areaName: '효자동' },
  'changseong-dong': { regionName: '서울', districtName: '종로구', areaName: '창성동' },
  'tongui-dong': { regionName: '서울', districtName: '종로구', areaName: '통의동' },
  'jeokseon-dong': { regionName: '서울', districtName: '종로구', areaName: '적선동' },
  'tongin-dong': { regionName: '서울', districtName: '종로구', areaName: '통인동' },
  'nusang-dong': { regionName: '서울', districtName: '종로구', areaName: '누상동' },
  'samcheong-dong': { regionName: '서울', districtName: '종로구', areaName: '삼청동' },
  'anguk-dong': { regionName: '서울', districtName: '종로구', areaName: '안국동' },
  'sogyeok-dong': { regionName: '서울', districtName: '종로구', areaName: '소격동' },
  'hwa-dong': { regionName: '서울', districtName: '종로구', areaName: '화동' },
  'sagan-dong': { regionName: '서울', districtName: '종로구', areaName: '사간동' },
  'songhyeon-dong': { regionName: '서울', districtName: '종로구', areaName: '송현동' },
  'gahoe-dong': { regionName: '서울', districtName: '종로구', areaName: '가회동' },
  'jae-dong': { regionName: '서울', districtName: '종로구', areaName: '재동' },
  'gye-dong': { regionName: '서울', districtName: '종로구', areaName: '계동' },
  'wonseo-dong': { regionName: '서울', districtName: '종로구', areaName: '원서동' },
  'insa-dong': { regionName: '서울', districtName: '종로구', areaName: '인사동' },
  'ikseon-dong': { regionName: '서울', districtName: '종로구', areaName: '익선동' },
  'gyeongun-dong': { regionName: '서울', districtName: '종로구', areaName: '경운동' },
  'gwanhun-dong': { regionName: '서울', districtName: '종로구', areaName: '관훈동' },
  'nagwon-dong': { regionName: '서울', districtName: '종로구', areaName: '낙원동' },
  'jongno': { regionName: '서울', districtName: '종로구', areaName: '종로1가~6가' },
  'ihwa-dong': { regionName: '서울', districtName: '종로구', areaName: '이화동' },
  'yeonji-dong': { regionName: '서울', districtName: '종로구', areaName: '연지동' },
  'dongsung-dong': { regionName: '서울', districtName: '종로구', areaName: '동숭동' },
  'hyehwa-dong': { regionName: '서울', districtName: '종로구', areaName: '혜화동' },
  'myeongnyun': { regionName: '서울', districtName: '종로구', areaName: '명륜1~4가' },
  
  // 경기 - 성남시
  'bundang-gu-seohyeon-dong': { regionName: '경기', districtName: '성남시', areaName: '분당구 서현동' },
  'bundang-gu-jeongja-dong': { regionName: '경기', districtName: '성남시', areaName: '분당구 정자동' },
  'bundang-gu-sunae-dong': { regionName: '경기', districtName: '성남시', areaName: '분당구 수내동' },
  'bundang-gu-yatap-dong': { regionName: '경기', districtName: '성남시', areaName: '분당구 야탑동' },
  'bundang-gu-imae-dong': { regionName: '경기', districtName: '성남시', areaName: '분당구 이매동' },
  'sujeong-gu-sinheung-dong': { regionName: '경기', districtName: '성남시', areaName: '수정구 신흥동' },
  'sujeong-gu-sujin-dong': { regionName: '경기', districtName: '성남시', areaName: '수정구 수진동' },
  'sujeong-gu-dandae-dong': { regionName: '경기', districtName: '성남시', areaName: '수정구 단대동' },
  'sujeong-gu-taepyeong-dong': { regionName: '경기', districtName: '성남시', areaName: '수정구 태평동' },
  'jungwon-gu-seongnam-dong': { regionName: '경기', districtName: '성남시', areaName: '중원구 성남동' },
  'jungwon-gu-geumgwang-dong': { regionName: '경기', districtName: '성남시', areaName: '중원구 금광동' },
  'jungwon-gu-eunhaeng-dong': { regionName: '경기', districtName: '성남시', areaName: '중원구 은행동' },
  'jungwon-gu-sangdaewon-dong': { regionName: '경기', districtName: '성남시', areaName: '중원구 상대원동' },
  
  // 경기 - 수원시
  'jangan-gu-pajang-dong': { regionName: '경기', districtName: '수원시', areaName: '장안구 파장동' },
  'jangan-gu-jeongja-dong': { regionName: '경기', districtName: '수원시', areaName: '장안구 정자동' },
  'jangan-gu-songjuk-dong': { regionName: '경기', districtName: '수원시', areaName: '장안구 송죽동' },
  'jangan-gu-jowon-dong': { regionName: '경기', districtName: '수원시', areaName: '장안구 조원동' },
  'jangan-gu-yeonmu-dong': { regionName: '경기', districtName: '수원시', areaName: '장안구 연무동' },
  'gwonseon-gu-seryu-dong': { regionName: '경기', districtName: '수원시', areaName: '권선구 세류동' },
  'gwonseon-gu-pyeong-dong': { regionName: '경기', districtName: '수원시', areaName: '권선구 평동' },
  'gwonseon-gu-seodun-dong': { regionName: '경기', districtName: '수원시', areaName: '권선구 서둔동' },
  'gwonseon-gu-guun-dong': { regionName: '경기', districtName: '수원시', areaName: '권선구 구운동' },
  'paldal-gu-maesan-dong': { regionName: '경기', districtName: '수원시', areaName: '팔달구 매산동' },
  'paldal-gu-maegyo-dong': { regionName: '경기', districtName: '수원시', areaName: '팔달구 매교동' },
  'paldal-gu-ingye-dong': { regionName: '경기', districtName: '수원시', areaName: '팔달구 인계동' },
  'paldal-gu-uman-dong': { regionName: '경기', districtName: '수원시', areaName: '팔달구 우만동' },
  'yeongtong-gu-yeongtong-dong': { regionName: '경기', districtName: '수원시', areaName: '영통구 영통동' },
  'yeongtong-gu-mangpo-dong': { regionName: '경기', districtName: '수원시', areaName: '영통구 망포동' },
  'yeongtong-gu-maetan-dong': { regionName: '경기', districtName: '수원시', areaName: '영통구 매탄동' },
  'yeongtong-gu-woncheon-dong': { regionName: '경기', districtName: '수원시', areaName: '영통구 원천동' },
  'yeongtong-gu-gwanggyo-dong': { regionName: '경기', districtName: '수원시', areaName: '영통구 광교동' },
  
  // 경기 - 고양시
  'ilsandong-gu-baekseok-dong': { regionName: '경기', districtName: '고양시', areaName: '일산동구 백석동' },
  'ilsandong-gu-madu-dong': { regionName: '경기', districtName: '고양시', areaName: '일산동구 마두동' },
  'ilsandong-gu-janghang-dong': { regionName: '경기', districtName: '고양시', areaName: '일산동구 장항동' },
  'ilsandong-gu-siksa-dong': { regionName: '경기', districtName: '고양시', areaName: '일산동구 식사동' },
  'ilsanseo-gu-juyeop-dong': { regionName: '경기', districtName: '고양시', areaName: '일산서구 주엽동' },
  'ilsanseo-gu-daeghwa-dong': { regionName: '경기', districtName: '고양시', areaName: '일산서구 대화동' },
  'ilsanseo-gu-tanhyeon-dong': { regionName: '경기', districtName: '고양시', areaName: '일산서구 탄현동' },
  'deogyang-gu-hwajeong-dong': { regionName: '경기', districtName: '고양시', areaName: '덕양구 화정동' },
  'deogyang-gu-haengsin-dong': { regionName: '경기', districtName: '고양시', areaName: '덕양구 행신동' },
  'deogyang-gu-neunggok-dong': { regionName: '경기', districtName: '고양시', areaName: '덕양구 능곡동' },
  'deogyang-gu-wondang-dong': { regionName: '경기', districtName: '고양시', areaName: '덕양구 원당동' },
  'deogyang-gu-samsong-dong': { regionName: '경기', districtName: '고양시', areaName: '덕양구 삼송동' },
  
  // 경기 - 용인시
  'suji-gu-jukjeon-dong': { regionName: '경기', districtName: '용인시', areaName: '수지구 죽전동' },
  'suji-gu-dongcheon-dong': { regionName: '경기', districtName: '용인시', areaName: '수지구 동천동' },
  'suji-gu-sinbong-dong': { regionName: '경기', districtName: '용인시', areaName: '수지구 신봉동' },
  'suji-gu-sanghyeon-dong': { regionName: '경기', districtName: '용인시', areaName: '수지구 상현동' },
  'giheung-gu-gugal-dong': { regionName: '경기', districtName: '용인시', areaName: '기흥구 구갈동' },
  'giheung-gu-bojeong-dong': { regionName: '경기', districtName: '용인시', areaName: '기흥구 보정동' },
  'giheung-gu-singal-dong': { regionName: '경기', districtName: '용인시', areaName: '기흥구 신갈동' },
  'giheung-gu-yeongdeok-dong': { regionName: '경기', districtName: '용인시', areaName: '기흥구 영덕동' },
  'cheoin-gu-gimryangjang-dong': { regionName: '경기', districtName: '용인시', areaName: '처인구 김량장동' },
  'cheoin-gu-yeokbuk-dong': { regionName: '경기', districtName: '용인시', areaName: '처인구 역북동' },
  'cheoin-gu-yubang-dong': { regionName: '경기', districtName: '용인시', areaName: '처인구 유방동' },
  'cheoin-gu-pogok-eup': { regionName: '경기', districtName: '용인시', areaName: '처인구 포곡읍' },
  'cheoin-gu-mohyeon-eup': { regionName: '경기', districtName: '용인시', areaName: '처인구 모현읍' },
  
  // 경기 - 부천시
  'wonmi-gu-jung-dong': { regionName: '경기', districtName: '부천시', areaName: '원미구 중동' },
  'wonmi-gu-sang-dong': { regionName: '경기', districtName: '부천시', areaName: '원미구 상동' },
  'wonmi-gu-simgok-dong': { regionName: '경기', districtName: '부천시', areaName: '원미구 심곡동' },
  'wonmi-gu-yakdae-dong': { regionName: '경기', districtName: '부천시', areaName: '원미구 약대동' },
  'sosa-gu-sosabon-dong': { regionName: '경기', districtName: '부천시', areaName: '소사구 소사본동' },
  'sosa-gu-songnae-dong': { regionName: '경기', districtName: '부천시', areaName: '소사구 송내동' },
  'sosa-gu-goean-dong': { regionName: '경기', districtName: '부천시', areaName: '소사구 괴안동' },
  'ojeong-gu-ojeong-dong': { regionName: '경기', districtName: '부천시', areaName: '오정구 오정동' },
  'ojeong-gu-gogang-dong': { regionName: '경기', districtName: '부천시', areaName: '오정구 고강동' },
  'ojeong-gu-wonjong-dong': { regionName: '경기', districtName: '부천시', areaName: '오정구 원종동' },
  
  // 경기 - 안산시
  'danwon-gu-gojan-dong': { regionName: '경기', districtName: '안산시', areaName: '단원구 고잔동' },
  'danwon-gu-choji-dong': { regionName: '경기', districtName: '안산시', areaName: '단원구 초지동' },
  'danwon-gu-wongok-dong': { regionName: '경기', districtName: '안산시', areaName: '단원구 원곡동' },
  'danwon-gu-seonbu-dong': { regionName: '경기', districtName: '안산시', areaName: '단원구 선부동' },
  'sangnok-gu-bono-dong': { regionName: '경기', districtName: '안산시', areaName: '상록구 본오동' },
  'sangnok-gu-sa-dong': { regionName: '경기', districtName: '안산시', areaName: '상록구 사동' },
  'sangnok-gu-wolpi-dong': { regionName: '경기', districtName: '안산시', areaName: '상록구 월피동' },
  'sangnok-gu-geongeon-dong': { regionName: '경기', districtName: '안산시', areaName: '상록구 건건동' },
  'sangnok-gu-seongpo-dong': { regionName: '경기', districtName: '안산시', areaName: '상록구 성포동' },
  
  // 경기 - 화성시
  'dongtan1': { regionName: '경기', districtName: '화성시', areaName: '동탄1신도시' },
  'dongtan2': { regionName: '경기', districtName: '화성시', areaName: '동탄2신도시' },
  'byeongjeom-dong': { regionName: '경기', districtName: '화성시', areaName: '병점동' },
  'hyangnam-eup': { regionName: '경기', districtName: '화성시', areaName: '향남읍' },
  'bongdam-eup': { regionName: '경기', districtName: '화성시', areaName: '봉담읍' },
  'ujeong-eup': { regionName: '경기', districtName: '화성시', areaName: '우정읍' },
  'namyang-eup': { regionName: '경기', districtName: '화성시', areaName: '남양읍' },
  
  // 경기 - 남양주시
  'dasan-dong-namyangju': { regionName: '경기', districtName: '남양주시', areaName: '다산동' },
  'byeollae-dong': { regionName: '경기', districtName: '남양주시', areaName: '별내동' },
  'hwado-eup': { regionName: '경기', districtName: '남양주시', areaName: '화도읍' },
  'jinjeop-eup': { regionName: '경기', districtName: '남양주시', areaName: '진접읍' },
  'onam-eup': { regionName: '경기', districtName: '남양주시', areaName: '오남읍' },
  'pyeongnae-dong': { regionName: '경기', districtName: '남양주시', areaName: '평내동' },
  'geumgok-dong-namyangju': { regionName: '경기', districtName: '남양주시', areaName: '금곡동' },
  'yangjeong-dong': { regionName: '경기', districtName: '남양주시', areaName: '양정동' },
  
  // 경기 - 평택시
  'pyeongtaek-dong': { regionName: '경기', districtName: '평택시', areaName: '평택동' },
  'songtan-dong': { regionName: '경기', districtName: '평택시', areaName: '송탄동' },
  'seojeong-dong': { regionName: '경기', districtName: '평택시', areaName: '서정동' },
  'jisan-dong': { regionName: '경기', districtName: '평택시', areaName: '지산동' },
  'sosabeol': { regionName: '경기', districtName: '평택시', areaName: '소사벌' },
  'godeok-sindo': { regionName: '경기', districtName: '평택시', areaName: '고덕신도시' },
  'cheongbuk-eup': { regionName: '경기', districtName: '평택시', areaName: '청북읍' },
  'anjung-eup': { regionName: '경기', districtName: '평택시', areaName: '안중읍' },
  
  // 경기 - 안양시
  'manan-gu-anyang-dong': { regionName: '경기', districtName: '안양시', areaName: '만안구 안양동' },
  'manan-gu-seoksu-dong': { regionName: '경기', districtName: '안양시', areaName: '만안구 석수동' },
  'dongan-gu-bisan-dong': { regionName: '경기', districtName: '안양시', areaName: '동안구 비산동' },
  'dongan-gu-gwanyang-dong': { regionName: '경기', districtName: '안양시', areaName: '동안구 관양동' },
  'dongan-gu-pyeongchon-dong': { regionName: '경기', districtName: '안양시', areaName: '동안구 평촌동' },
  'dongan-gu-hogye-dong': { regionName: '경기', districtName: '안양시', areaName: '동안구 호계동' },
  'dongan-gu-beomgye-dong': { regionName: '경기', districtName: '안양시', areaName: '동안구 범계동' },
  
  // 경기 - 시흥시
  'jeongwang-dong': { regionName: '경기', districtName: '시흥시', areaName: '정왕동' },
  'daeya-dong': { regionName: '경기', districtName: '시흥시', areaName: '대야동' },
  'sincheon-dong-siheung': { regionName: '경기', districtName: '시흥시', areaName: '신천동' },
  'eunhaeng-dong-siheung': { regionName: '경기', districtName: '시흥시', areaName: '은행동' },
  'janggok-dong': { regionName: '경기', districtName: '시흥시', areaName: '장곡동' },
  'wolgot-dong': { regionName: '경기', districtName: '시흥시', areaName: '월곶동' },
  
  // 경기 - 파주시
  'unjeong-dong': { regionName: '경기', districtName: '파주시', areaName: '운정동' },
  'geumchon-dong': { regionName: '경기', districtName: '파주시', areaName: '금촌동' },
  'gyoha-eup': { regionName: '경기', districtName: '파주시', areaName: '교하읍' },
  'munsan-eup': { regionName: '경기', districtName: '파주시', areaName: '문산읍' },
  'jori-eup': { regionName: '경기', districtName: '파주시', areaName: '조리읍' },
  
  // 경기 - 의정부시
  'uijeongbu-dong': { regionName: '경기', districtName: '의정부시', areaName: '의정부동' },
  'howon-dong': { regionName: '경기', districtName: '의정부시', areaName: '호원동' },
  'jangam-dong': { regionName: '경기', districtName: '의정부시', areaName: '장암동' },
  'singok-dong': { regionName: '경기', districtName: '의정부시', areaName: '신곡동' },
  'ganeung-dong': { regionName: '경기', districtName: '의정부시', areaName: '가능동' },
  'nogyang-dong': { regionName: '경기', districtName: '의정부시', areaName: '녹양동' },
  
  // 경기 - 김포시
  'janggi-dong': { regionName: '경기', districtName: '김포시', areaName: '장기동' },
  'gurae-dong': { regionName: '경기', districtName: '김포시', areaName: '구래동' },
  'masan-dong': { regionName: '경기', districtName: '김포시', areaName: '마산동' },
  'sau-dong': { regionName: '경기', districtName: '김포시', areaName: '사우동' },
  'pungmu-dong': { regionName: '경기', districtName: '김포시', areaName: '풍무동' },
  'gochon-eup': { regionName: '경기', districtName: '김포시', areaName: '고촌읍' },
  'yangchon-eup': { regionName: '경기', districtName: '김포시', areaName: '양촌읍' },
  
  // 경기 - 광주시
  'gyeongan-dong': { regionName: '경기', districtName: '광주시', areaName: '경안동' },
  'songjeong-dong-gwangju': { regionName: '경기', districtName: '광주시', areaName: '송정동' },
  'ssangnyeong-dong': { regionName: '경기', districtName: '광주시', areaName: '쌍령동' },
  'yeok-dong': { regionName: '경기', districtName: '광주시', areaName: '역동' },
  'tanbeol-dong': { regionName: '경기', districtName: '광주시', areaName: '탄벌동' },
  'opo-eup': { regionName: '경기', districtName: '광주시', areaName: '오포읍' },
  'gonjiam-eup': { regionName: '경기', districtName: '광주시', areaName: '곤지암읍' },
  
  // 경기 - 광명시
  'cheolsan-dong': { regionName: '경기', districtName: '광명시', areaName: '철산동' },
  'gwangmyeong-dong': { regionName: '경기', districtName: '광명시', areaName: '광명동' },
  'haan-dong': { regionName: '경기', districtName: '광명시', areaName: '하안동' },
  'soha-dong': { regionName: '경기', districtName: '광명시', areaName: '소하동' },
  
  // 경기 - 군포시
  'sanbon-dong': { regionName: '경기', districtName: '군포시', areaName: '산본동' },
  'geumjeong-dong-gunpo': { regionName: '경기', districtName: '군포시', areaName: '금정동' },
  'dangjeong-dong': { regionName: '경기', districtName: '군포시', areaName: '당정동' },
  'dang-dong': { regionName: '경기', districtName: '군포시', areaName: '당동' },
  'gunpo-dong': { regionName: '경기', districtName: '군포시', areaName: '군포동' },
  
  // 경기 - 하남시
  'sinjang-dong': { regionName: '경기', districtName: '하남시', areaName: '신장동' },
  'gambuk-dong': { regionName: '경기', districtName: '하남시', areaName: '감북동' },
  'gamil-dong': { regionName: '경기', districtName: '하남시', areaName: '감일동' },
  'changwoo-dong': { regionName: '경기', districtName: '하남시', areaName: '창우동' },
  'deokpung-dong': { regionName: '경기', districtName: '하남시', areaName: '덕풍동' },
  'misa-dong': { regionName: '경기', districtName: '하남시', areaName: '미사동' },
  
  // 경기 - 오산시
  'osan-dong': { regionName: '경기', districtName: '오산시', areaName: '오산동' },
  'won-dong': { regionName: '경기', districtName: '오산시', areaName: '원동' },
  'segyo-dong': { regionName: '경기', districtName: '오산시', areaName: '세교동' },
  'galgot-dong': { regionName: '경기', districtName: '오산시', areaName: '갈곶동' },
  
  // 경기 - 이천시
  'jungri-dong': { regionName: '경기', districtName: '이천시', areaName: '중리동' },
  'changjeon-dong': { regionName: '경기', districtName: '이천시', areaName: '창전동' },
  'gwango-dong': { regionName: '경기', districtName: '이천시', areaName: '관고동' },
  'jeungpo-dong': { regionName: '경기', districtName: '이천시', areaName: '증포동' },
  'bubal-eup': { regionName: '경기', districtName: '이천시', areaName: '부발읍' },
  'sindun-myeon': { regionName: '경기', districtName: '이천시', areaName: '신둔면' },
  
  // 인천 - 남동구
  'guwol-dong': { regionName: '인천', districtName: '남동구', areaName: '구월동' },
  'ganseok-dong': { regionName: '인천', districtName: '남동구', areaName: '간석동' },
  'mansu-dong': { regionName: '인천', districtName: '남동구', areaName: '만수동' },
  'jangsu-dong': { regionName: '인천', districtName: '남동구', areaName: '장수동' },
  'seochang-dong': { regionName: '인천', districtName: '남동구', areaName: '서창동' },
  'unyeon-dong': { regionName: '인천', districtName: '남동구', areaName: '운연동' },
  
  // 인천 - 연수구
  'songdo-dong': { regionName: '인천', districtName: '연수구', areaName: '송도동' },
  'okyeon-dong': { regionName: '인천', districtName: '연수구', areaName: '옥련동' },
  'dongchun-dong': { regionName: '인천', districtName: '연수구', areaName: '동춘동' },
  'cheonghak-dong': { regionName: '인천', districtName: '연수구', areaName: '청학동' },
  'seonhak-dong': { regionName: '인천', districtName: '연수구', areaName: '선학동' },
  'yeonsu-dong': { regionName: '인천', districtName: '연수구', areaName: '연수동' },
  
  // 인천 - 부평구
  'bupyeong-dong': { regionName: '인천', districtName: '부평구', areaName: '부평동' },
  'sangok-dong': { regionName: '인천', districtName: '부평구', areaName: '산곡동' },
  'cheongcheon-dong': { regionName: '인천', districtName: '부평구', areaName: '청천동' },
  'galsan-dong': { regionName: '인천', districtName: '부평구', areaName: '갈산동' },
  'samsan-dong': { regionName: '인천', districtName: '부평구', areaName: '삼산동' },
  'bugae-dong': { regionName: '인천', districtName: '부평구', areaName: '부개동' },
  'sipjeong-dong': { regionName: '인천', districtName: '부평구', areaName: '십정동' },
  
  // 인천 - 계양구
  'jakjeon-dong': { regionName: '인천', districtName: '계양구', areaName: '작전동' },
  'hyoseong-dong': { regionName: '인천', districtName: '계양구', areaName: '효성동' },
  'gyesan-dong': { regionName: '인천', districtName: '계양구', areaName: '계산동' },
  'imhak-dong': { regionName: '인천', districtName: '계양구', areaName: '임학동' },
  'dongyang-dong': { regionName: '인천', districtName: '계양구', areaName: '동양동' },
  'gyulhyeon-dong': { regionName: '인천', districtName: '계양구', areaName: '귤현동' },
  'byeongbang-dong': { regionName: '인천', districtName: '계양구', areaName: '병방동' },
  'bakchon-dong': { regionName: '인천', districtName: '계양구', areaName: '박촌동' },
  
  // 인천 - 서구
  'geomdan-dong': { regionName: '인천', districtName: '서구', areaName: '검단동' },
  'wondang-dong-incheon': { regionName: '인천', districtName: '서구', areaName: '원당동' },
  'gajwa-dong': { regionName: '인천', districtName: '서구', areaName: '가좌동' },
  'seoknam-dong': { regionName: '인천', districtName: '서구', areaName: '석남동' },
  'gajeong-dong-incheon': { regionName: '인천', districtName: '서구', areaName: '가정동' },
  'sinhyeon-dong': { regionName: '인천', districtName: '서구', areaName: '신현동' },
  'geomam-dong': { regionName: '인천', districtName: '서구', areaName: '검암동' },
  'yeonhui-dong-incheon': { regionName: '인천', districtName: '서구', areaName: '연희동' },
  
  // 인천 - 미추홀구
  'sungui-dong': { regionName: '인천', districtName: '미추홀구', areaName: '숭의동' },
  'yonghyeon-dong': { regionName: '인천', districtName: '미추홀구', areaName: '용현동' },
  'hakik-dong': { regionName: '인천', districtName: '미추홀구', areaName: '학익동' },
  'juan-dong': { regionName: '인천', districtName: '미추홀구', areaName: '주안동' },
  'gwangyo-dong': { regionName: '인천', districtName: '미추홀구', areaName: '관교동' },
  'munhak-dong': { regionName: '인천', districtName: '미추홀구', areaName: '문학동' },
  
  // 인천 - 중구
  'sinpo-dong': { regionName: '인천', districtName: '중구', areaName: '신포동' },
  'dap-dong': { regionName: '인천', districtName: '중구', areaName: '답동' },
  'yeonan-dong': { regionName: '인천', districtName: '중구', areaName: '연안동' },
  'sinsaeng-dong': { regionName: '인천', districtName: '중구', areaName: '신생동' },
  'bukseong-dong': { regionName: '인천', districtName: '중구', areaName: '북성동' },
  'seonhwa-dong': { regionName: '인천', districtName: '중구', areaName: '선화동' },
  'yu-dong': { regionName: '인천', districtName: '중구', areaName: '유동' },
  'songwol-dong': { regionName: '인천', districtName: '중구', areaName: '송월동' },
  'songlim-dong-incheon': { regionName: '인천', districtName: '중구', areaName: '송림동' },
  'yeongjongdo': { regionName: '인천', districtName: '중구', areaName: '영종도' },
  'yongyudo': { regionName: '인천', districtName: '중구', areaName: '용유도' },
  
  // 인천 - 동구
  'manseok-dong': { regionName: '인천', districtName: '동구', areaName: '만석동' },
  'hwasu-dong': { regionName: '인천', districtName: '동구', areaName: '화수동' },
  'songhyeon-dong-incheon': { regionName: '인천', districtName: '동구', areaName: '송현동' },
  'geumgok-dong-incheon': { regionName: '인천', districtName: '동구', areaName: '금곡동' },
  'hwapyeong-dong': { regionName: '인천', districtName: '동구', areaName: '화평동' },
  
  // 경상도 - 부산광역시
  'haeundae-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '해운대구' },
  'nam-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '남구' },
  'dongnae-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '동래구' },
  'busanjin-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '부산진구' },
  'suyeong-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '수영구' },
  'yeonje-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '연제구' },
  'sasang-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '사상구' },
  'saha-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '사하구' },
  'gangseo-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '강서구' },
  'geumjeong-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '금정구' },
  'buk-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '북구' },
  'seo-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '서구' },
  'jung-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '중구' },
  'dong-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '동구' },
  'yeongdo-gu': { regionName: '경상도', districtName: '부산광역시', areaName: '영도구' },
  
  // 경상도 - 대구광역시
  'suseong-gu': { regionName: '경상도', districtName: '대구광역시', areaName: '수성구' },
  'dalseo-gu': { regionName: '경상도', districtName: '대구광역시', areaName: '달서구' },
  'dalseong-gun': { regionName: '경상도', districtName: '대구광역시', areaName: '달성군' },
  
  // 경상도 - 울산광역시
  'ulju-gun': { regionName: '경상도', districtName: '울산광역시', areaName: '울주군' },
  
  // 경상도 - 경남
  'changwon-ui-chang-gu': { regionName: '경상도', districtName: '경남', areaName: '창원시 의창구' },
  'changwon-eui-seongsan-gu': { regionName: '경상도', districtName: '경남', areaName: '창원시 성산구' },
  'changwon-eui-masanhwop-gu': { regionName: '경상도', districtName: '경남', areaName: '창원시 마산회원구' },
  'changwon-eui-masanhap-gu': { regionName: '경상도', districtName: '경남', areaName: '창원시 마산합포구' },
  'changwon-eui-jinhae-gu': { regionName: '경상도', districtName: '경남', areaName: '창원시 진해구' },
  'gimhae-si': { regionName: '경상도', districtName: '경남', areaName: '김해시' },
  'yangsan-si': { regionName: '경상도', districtName: '경남', areaName: '양산시' },
  'jinju-si': { regionName: '경상도', districtName: '경남', areaName: '진주시' },
  'geoje-si': { regionName: '경상도', districtName: '경남', areaName: '거제시' },
  'tongyeong-si': { regionName: '경상도', districtName: '경남', areaName: '통영시' },
  'sacheon-si': { regionName: '경상도', districtName: '경남', areaName: '사천시' },
  'miryang-si': { regionName: '경상도', districtName: '경남', areaName: '밀양시' },
  'haman-gun': { regionName: '경상도', districtName: '경남', areaName: '함안군' },
  'geochang-gun': { regionName: '경상도', districtName: '경남', areaName: '거창군' },
  'changnyeong-gun': { regionName: '경상도', districtName: '경남', areaName: '창녕군' },
  'goseong-gun': { regionName: '경상도', districtName: '경남', areaName: '고성군' },
  'hadong-gun': { regionName: '경상도', districtName: '경남', areaName: '하동군' },
  'hapcheon-gun': { regionName: '경상도', districtName: '경남', areaName: '합천군' },
  'namhae-gun': { regionName: '경상도', districtName: '경남', areaName: '남해군' },
  'hamyang-gun': { regionName: '경상도', districtName: '경남', areaName: '함양군' },
  'sancheong-gun': { regionName: '경상도', districtName: '경남', areaName: '산청군' },
  'uiryeong-gun': { regionName: '경상도', districtName: '경남', areaName: '의령군' },
  
  // 경상도 - 경북
  'pohang-nam-gu': { regionName: '경상도', districtName: '경북', areaName: '포항시 남구' },
  'pohang-buk-gu': { regionName: '경상도', districtName: '경북', areaName: '포항시 북구' },
  'gyeongju-si': { regionName: '경상도', districtName: '경북', areaName: '경주시' },
  'gumi-si': { regionName: '경상도', districtName: '경북', areaName: '구미시' },
  'andong-si': { regionName: '경상도', districtName: '경북', areaName: '안동시' },
  'gyeongsan-si': { regionName: '경상도', districtName: '경북', areaName: '경산시' },
  'yeongcheon-si': { regionName: '경상도', districtName: '경북', areaName: '영천시' },
  'sangju-si': { regionName: '경상도', districtName: '경북', areaName: '상주시' },
  'mungyeong-si': { regionName: '경상도', districtName: '경북', areaName: '문경시' },
  'gimcheon-si': { regionName: '경상도', districtName: '경북', areaName: '김천시' },
  'yeongju-si': { regionName: '경상도', districtName: '경북', areaName: '영주시' },
  'chilgok-gun': { regionName: '경상도', districtName: '경북', areaName: '칠곡군' },
  'yeongdeok-gun': { regionName: '경상도', districtName: '경북', areaName: '영덕군' },
  'cheongsong-gun': { regionName: '경상도', districtName: '경북', areaName: '청송군' },
  'goryeong-gun': { regionName: '경상도', districtName: '경북', areaName: '고령군' },
  'seongju-gun': { regionName: '경상도', districtName: '경북', areaName: '성주군' },
  'yecheon-gun': { regionName: '경상도', districtName: '경북', areaName: '예천군' },
  'bonghwa-gun': { regionName: '경상도', districtName: '경북', areaName: '봉화군' },
  'uljin-gun': { regionName: '경상도', districtName: '경북', areaName: '울진군' },
  'uiseong-gun': { regionName: '경상도', districtName: '경북', areaName: '의성군' },
  'cheongdo-gun': { regionName: '경상도', districtName: '경북', areaName: '청도군' },
  'gunwi-gun': { regionName: '경상도', districtName: '경북', areaName: '군위군' },
  
  // 전라도 - 광주광역시
  'gwangju-seo': { regionName: '전라도', districtName: '광주광역시', areaName: '서구' },
  'gwangju-gwangsan': { regionName: '전라도', districtName: '광주광역시', areaName: '광산구' },
  
  // 전라도 - 전북
  'jeonju-wansan': { regionName: '전라도', districtName: '전북', areaName: '전주시 완산구' },
  'jeonju-deokjin': { regionName: '전라도', districtName: '전북', areaName: '전주시 덕진구' },
  'iksan': { regionName: '전라도', districtName: '전북', areaName: '익산시' },
  'gunsan': { regionName: '전라도', districtName: '전북', areaName: '군산시' },
  'jeongeup': { regionName: '전라도', districtName: '전북', areaName: '정읍시' },
  'namwon': { regionName: '전라도', districtName: '전북', areaName: '남원시' },
  'gimje': { regionName: '전라도', districtName: '전북', areaName: '김제시' },
  'wanju': { regionName: '전라도', districtName: '전북', areaName: '완주군' },
  'imsil': { regionName: '전라도', districtName: '전북', areaName: '임실군' },
  'sunchang': { regionName: '전라도', districtName: '전북', areaName: '순창군' },
  'gochang': { regionName: '전라도', districtName: '전북', areaName: '고창군' },
  'buan': { regionName: '전라도', districtName: '전북', areaName: '부안군' },
  'muju': { regionName: '전라도', districtName: '전북', areaName: '무주군' },
  'jinan': { regionName: '전라도', districtName: '전북', areaName: '진안군' },
  'jangsu': { regionName: '전라도', districtName: '전북', areaName: '장수군' },
  
  // 전라도 - 전남
  'mokpo': { regionName: '전라도', districtName: '전남', areaName: '목포시' },
  'yeosu': { regionName: '전라도', districtName: '전남', areaName: '여수시' },
  'suncheon': { regionName: '전라도', districtName: '전남', areaName: '순천시' },
  'naju': { regionName: '전라도', districtName: '전남', areaName: '나주시' },
  'gwangyang': { regionName: '전라도', districtName: '전남', areaName: '광양시' },
  'damyang': { regionName: '전라도', districtName: '전남', areaName: '담양군' },
  'gokseong': { regionName: '전라도', districtName: '전남', areaName: '곡성군' },
  'gurye': { regionName: '전라도', districtName: '전남', areaName: '구례군' },
  'goheung': { regionName: '전라도', districtName: '전남', areaName: '고흥군' },
  'boseong': { regionName: '전라도', districtName: '전남', areaName: '보성군' },
  'hwasun': { regionName: '전라도', districtName: '전남', areaName: '화순군' },
  'jangheung': { regionName: '전라도', districtName: '전남', areaName: '장흥군' },
  'gangjin': { regionName: '전라도', districtName: '전남', areaName: '강진군' },
  'haenam': { regionName: '전라도', districtName: '전남', areaName: '해남군' },
  'yeongam': { regionName: '전라도', districtName: '전남', areaName: '영암군' },
  'muan': { regionName: '전라도', districtName: '전남', areaName: '무안군' },
  'hampyeong': { regionName: '전라도', districtName: '전남', areaName: '함평군' },
  'yeonggwang': { regionName: '전라도', districtName: '전남', areaName: '영광군' },
  'jangseong': { regionName: '전라도', districtName: '전남', areaName: '장성군' },
  'wando': { regionName: '전라도', districtName: '전남', areaName: '완도군' },
  'jindo': { regionName: '전라도', districtName: '전남', areaName: '진도군' },
  'sinan': { regionName: '전라도', districtName: '전남', areaName: '신안군' },
}
